name: docker-pipeline

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
env:
    DOCKER_USERNAME: ${{vars.DOCUSER}}
    version: ${{vars.VERSION}}

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Docker Login
          uses: docker/login-action@v3.3.0
          with:
                username: $DOCKER_USERNAME
                password: ${{secrets.DOCKER_PASSWORD}}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{secrets.DOCKER_USERNAME}}/actions:$version 